# application: banksy-staging-1
# version: 1
runtime: custom
# runtime: go
# api_version: go1
vm: true
# api_version: go1
# instance_class: B2
# basic_scaling:
#   max_instances: 5
#   idle_timeout: 10m

# handlers:
# - url: /.*
#   script: _go_app

# - url: .*
#   script: images.go
#   secure: always

health_check:
  enable_health_check: False

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.9
